apiVersion: v1
kind: Service
metadata:
    name: lifeindevopspipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: lifeindevopspipelinesjavascriptdocker